export const SPECIAL_FOLDERS = {
  SELECTED:   '__selected',
  DUST:       '__dust',
  THUMBNAILS: '__thumbnails',
} as const;

export const STORAGE_KEYS = {
  SORT_BY:       'pp_sortBy',
  SORT_ASC:      'pp_sortAsc',
  LMS_MODEL:     'lmstudioModel',
  GEN_STEPS:     'pp_gen_steps',
  GEN_CFG:       'pp_gen_cfg',
  GEN_SAMPLER:        'pp_gen_samplerName',
  GEN_SCHEDULER:      'pp_gen_scheduler',
  GEN_WIDTH:          'pp_gen_width',
  GEN_HEIGHT:         'pp_gen_height',
  GEN_BATCH:          'pp_gen_batchSize',
  GEN_LORA_STEP:      'pp_gen_lora_step',
  GEN_POS_PROMPT:     'pp_gen_positivePrompt',
  GEN_NEG_PROMPT:     'pp_gen_negativePrompt',
  GEN_PROMPT_HISTORY: 'pp_gen_promptHistory',
  FAVORITES_PREFIX:   'pp_favorites:',
  COMFY_POS:          'pp_comfy_pos',
  WIDGET_POS:         'pp_widget_pos',
  LMSTUDIO_POS:       'pp_lmstudio_pos',
  JOBS_POS:           'pp_jobs_pos',
  SYNOPSIS_STORYTELLER_MODEL: 'pp_synopsis_storyteller_model',
  SYNOPSIS_ILLUSTRATOR_MODEL: 'pp_synopsis_illustrator_model',
  SYNOPSIS_STYLE:     'pp_synopsis_style',
  SYNOPSIS_MIN:       'pp_synopsis_min',
  SYNOPSIS_MAX:       'pp_synopsis_max',
  DICTIONARIES:       'pp_dictionaries',
  DICTIONARY_LIST_WIDTH: 'pp_dictionary_list_width',
  DICTIONARY_DIALOG_SIZE: 'pp_dictionary_dialog_size',
  COLLECTION_LAYOUT:  'pp_collection_layout',
  CAMERA_CHART_MODE:  'pp_camera_chart_mode',
  CHART_SET_PREFIX:   'pp_chart_set:',
} as const;
